import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["import", "typescript", "unicorn", "promise"],
  env: {
    es2024: true,
    node: true,
  },
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "warn",
    pedantic: "warn",
  },
  rules: {
    "no-console": "error",
    eqeqeq: "error",
    // Turned off deliberately. The resolver's compile-fetch-retry loop and the
    // worker pool's drain both have to await inside a loop by construction —
    // each iteration depends on the previous one's result.
    "no-await-in-loop": "off",
    "typescript/consistent-type-imports": "error",
    "typescript/no-explicit-any": "error",
    "unicorn/prefer-node-protocol": "error",
    "import/no-default-export": "error",
    // This codebase annotates fields and branches with trailing comments as a
    // matter of style. The rule would move every one of them onto its own
    // line, which reads worse and says nothing about correctness.
    "no-inline-comments": "off",
    // Comments are a large share of the lines here by design. Counting them
    // toward a length limit would push explanation out of the files that need
    // it most.
    "max-lines": ["warn", { max: 500, skipComments: true }],
  },
  overrides: [
    {
      files: ["*.config.js", "*.config.ts"],
      rules: {
        "import/no-default-export": "off",
      },
    },
    {
      files: [
        "**/test/**",
        "**/*.test.ts",
        "**/*.test.js",
        "**/bench/**",
        // The Puppeteer comparison. Same category as `bench/`, but it lives
        // outside the pnpm workspace so that Puppeteer can never become a
        // dependency of a published package — which also puts it outside the
        // glob above.
        "benchmarks/**",
        // Maintenance scripts: run by hand, and reporting what they did is the
        // whole point of them.
        "**/scripts/**",
      ],
      rules: {
        "no-console": "off",
        "max-lines": "off",
        "max-lines-per-function": "off",
        "no-underscore-dangle": "off",
        // Fixtures are written for readability over ceremony.
        "require-await": "off",
        // Benchmarks deliberately start work without awaiting it — running
        // compiles concurrently is the thing being measured.
        "unicorn/prefer-top-level-await": "off",
      },
    },
  ],
  ignorePatterns: [
    "target/**",
    "dist/**",
    "**/*.node",
    // Generated by napi-rs. Regenerated on every build, so a lint fix here
    // would be silently reverted.
    "packages/binding/index.js",
    "packages/binding/index.d.ts",
  ],
});
