// Copy the default Typst fonts out of the vendored `typst-assets` crate and
// regenerate `src/manifest.ts`.
//
//   node scripts/sync.mjs
//
// Run this deliberately, when the pinned Typst version changes — never
// automatically. The output is committed so that a font byte changing shows up
// as a reviewed diff with a new checksum, which is the only way anyone would
// notice a silent upstream substitution.
//
// **The files are copied verbatim and must stay that way.** `NewCM10-Regular`
// is GPL-3.0-or-later, and the Distribution Exception that lets an MIT-adjacent
// package carry it is void the moment glyphs are added, removed, or re-encoded.
// Subsetting these to save space would relicense this package as GPL-3. See
// ../../LICENSING.md.

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL("..", import.meta.url));
const REPO = fileURLToPath(new URL("../../..", import.meta.url));

// The exact 17 files `typst_assets::fonts()` yields, in its order, with the
// license each one actually carries. Transcribed from the crate's `NOTICE`.
// Note that this is *not* every font in the crate: the 14 Foxit `.pfb` files
// are PDF base-14 substitutes used internally by typst-pdf, not text fonts, and
// they are not part of this package.
const FONTS = [
  ["LibertinusSerif-Regular.otf", "OFL-1.1"],
  ["LibertinusSerif-Bold.otf", "OFL-1.1"],
  ["LibertinusSerif-Italic.otf", "OFL-1.1"],
  ["LibertinusSerif-BoldItalic.otf", "OFL-1.1"],
  ["LibertinusSerif-Semibold.otf", "OFL-1.1"],
  ["LibertinusSerif-SemiboldItalic.otf", "OFL-1.1"],
  ["NewCMMath-Bold.otf", "LPPL-1.3c"],
  ["NewCMMath-Book.otf", "LPPL-1.3c"],
  ["NewCMMath-Regular.otf", "LPPL-1.3c"],
  ["NewCM10-Regular.otf", "GPL-3.0-or-later"],
  ["NewCM10-Bold.otf", "LPPL-1.3c"],
  ["NewCM10-Italic.otf", "LPPL-1.3c"],
  ["NewCM10-BoldItalic.otf", "LPPL-1.3c"],
  ["DejaVuSansMono-Bold.ttf", "Bitstream-Vera"],
  ["DejaVuSansMono-BoldOblique.ttf", "Bitstream-Vera"],
  ["DejaVuSansMono-Oblique.ttf", "Bitstream-Vera"],
  ["DejaVuSansMono.ttf", "Bitstream-Vera"],
];

function assetsRoot() {
  const meta = JSON.parse(
    execFileSync("cargo", ["metadata", "--format-version", "1"], {
      cwd: REPO,
      maxBuffer: 64 * 1024 * 1024,
      encoding: "utf8",
    }),
  );
  const pkg = meta.packages.find((p) => p.name === "typst-assets");
  if (!pkg) throw new Error("typst-assets is not in the cargo metadata; run `cargo fetch`");
  return { dir: join(pkg.manifest_path, ".."), version: pkg.version };
}

const { dir, version } = assetsRoot();
mkdirSync(join(HERE, "fonts"), { recursive: true });
mkdirSync(join(HERE, "licenses"), { recursive: true });

// The crate's NOTICE carries the full text of all four licenses. Reproducing it
// wholesale is the only way to be certain none is missed.
copyFileSync(join(dir, "NOTICE"), join(HERE, "licenses", "NOTICE"));

const entries = FONTS.map(([file, license]) => {
  const bytes = readFileSync(join(dir, "files", "fonts", file));
  writeFileSync(join(HERE, "fonts", file), bytes);
  return {
    file,
    license,
    bytes: bytes.length,
    sha256: createHash("sha256").update(bytes).digest("hex"),
  };
});

const total = entries.reduce((sum, entry) => sum + entry.bytes, 0);

writeFileSync(
  join(HERE, "src", "manifest.ts"),
  `// GENERATED by scripts/sync.mjs from typst-assets ${version}. Do not edit.
//
// The checksums are the point. They turn "ship the fonts byte-for-byte" from a
// rule someone has to remember into one the test suite enforces — see
// ../../../LICENSING.md for why modifying these files would relicense this
// package as GPL-3.

/** The typst-assets release these files were taken from. */
export const TYPST_ASSETS_VERSION = ${JSON.stringify(version)};

/** Total size of the shipped font files, in bytes. */
export const TOTAL_BYTES = ${total};

export interface FontEntry {
  /** Filename under \`fonts/\`. Preserved exactly: OFL-1.1 restricts renaming. */
  file: string;
  /** SPDX identifier for this file specifically, not for the set. */
  license: string;
  bytes: number;
  sha256: string;
}

export const MANIFEST: readonly FontEntry[] = ${JSON.stringify(entries, null, 2)};
`,
);

console.log(
  `synced ${entries.length} fonts (${(total / 1024 / 1024).toFixed(1)} MB) from typst-assets ${version}`,
);
