// GENERATED by scripts/sync.mjs from typst-assets 0.15.1. Do not edit.
//
// The checksums are the point. They turn "ship the fonts byte-for-byte" from a
// rule someone has to remember into one the test suite enforces — see
// ../../../LICENSING.md for why modifying these files would relicense this
// package as GPL-3.

/** The typst-assets release these files were taken from. */
export const TYPST_ASSETS_VERSION = "0.15.1";

/** Total size of the shipped font files, in bytes. */
export const TOTAL_BYTES = 9683068;

export interface FontEntry {
  /** Filename under `fonts/`. Preserved exactly: OFL-1.1 restricts renaming. */
  file: string;
  /** SPDX identifier for this file specifically, not for the set. */
  license: string;
  bytes: number;
  sha256: string;
}

export const MANIFEST: readonly FontEntry[] = [
  {
    file: "LibertinusSerif-Regular.otf",
    license: "OFL-1.1",
    bytes: 337132,
    sha256: "fcf06307a77367394fcb0ccb241e59eea70dba3d732be309647611224679c733",
  },
  {
    file: "LibertinusSerif-Bold.otf",
    license: "OFL-1.1",
    bytes: 293908,
    sha256: "0264914210ed51b3231ebc92ce529e9f2e166ba9eebf0cd4a579558690a27b64",
  },
  {
    file: "LibertinusSerif-Italic.otf",
    license: "OFL-1.1",
    bytes: 332312,
    sha256: "9a393d63d6e05f620d3dc0190dfd35a8ede58c0808cf0fc9de7fcb9c723e4c24",
  },
  {
    file: "LibertinusSerif-BoldItalic.otf",
    license: "OFL-1.1",
    bytes: 259176,
    sha256: "47a665259f09f554f5d133d7718cdad43ff462c6a6b2328f38023465e62d57ce",
  },
  {
    file: "LibertinusSerif-Semibold.otf",
    license: "OFL-1.1",
    bytes: 291640,
    sha256: "a4b3f28e85881db34695c1f005e4c79233a6caf3a2bd286c9b418c025fb99308",
  },
  {
    file: "LibertinusSerif-SemiboldItalic.otf",
    license: "OFL-1.1",
    bytes: 343148,
    sha256: "397f0d7aba35ae6a988948ae046c14c6b1e0d270fcc6e292b8bc29fd625c6101",
  },
  {
    file: "NewCMMath-Bold.otf",
    license: "LPPL-1.3c",
    bytes: 1232148,
    sha256: "c6c0e060da57d4f44274705afb956013047231dc62be5a4b02a351ab0dc43f2f",
  },
  {
    file: "NewCMMath-Book.otf",
    license: "LPPL-1.3c",
    bytes: 1432068,
    sha256: "2ea09ebc9167b1e1a66f31390dc917f2d4004ecfca72d51b28010e4ad6becd95",
  },
  {
    file: "NewCMMath-Regular.otf",
    license: "LPPL-1.3c",
    bytes: 1306268,
    sha256: "d66ac1cc91c55c24d3636ae2df1238076debdff51841f9893fc5419cc2df3df7",
  },
  {
    file: "NewCM10-Regular.otf",
    license: "GPL-3.0-or-later",
    bytes: 717588,
    sha256: "328698d764ccdf7acf6bc1088aefd83a237f6a1d8b812de1e77ac5e4483bf3d1",
  },
  {
    file: "NewCM10-Bold.otf",
    license: "LPPL-1.3c",
    bytes: 629288,
    sha256: "40b0b32b63655fe802679ee4a14adb29c762a4712095d9c84cf7df7852b5152e",
  },
  {
    file: "NewCM10-Italic.otf",
    license: "LPPL-1.3c",
    bytes: 721176,
    sha256: "a55d07607eec48889b6e7e7d51d7703c3beb915a39690f34fe01b4e2a744a9d6",
  },
  {
    file: "NewCM10-BoldItalic.otf",
    license: "LPPL-1.3c",
    bytes: 609000,
    sha256: "fb53f43500c8ffbcc6dfdea5a519961d475543174ea2a0dcbe16c08510299fdf",
  },
  {
    file: "DejaVuSansMono-Bold.ttf",
    license: "Bitstream-Vera",
    bytes: 331992,
    sha256: "bce60f1b4421acd9ea51ba6623d7024ecbe6817a953e3654df62a5e6bdf8f769",
  },
  {
    file: "DejaVuSansMono-BoldOblique.ttf",
    license: "Bitstream-Vera",
    bytes: 253580,
    sha256: "91713a71d550bba22c2a6b2bb2a9ad8f9a159e12e4e9f0a5b2677998ba21213e",
  },
  {
    file: "DejaVuSansMono-Oblique.ttf",
    license: "Bitstream-Vera",
    bytes: 251932,
    sha256: "742097840c541870e8d6dc5c9b37bb1ceeea6c0dedd1d475faf903ef9df734b0",
  },
  {
    file: "DejaVuSansMono.ttf",
    license: "Bitstream-Vera",
    bytes: 340712,
    sha256: "b4a6c3e4faab8773f4ff761d56451646409f29abedd68f05d38c2df667d3c582",
  },
];
