/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A long-lived compiler. Cheap to share, expensive to construct. */
export declare class Compiler {
  constructor(options: CompilerOptions)
  /**
   * Compile on a pool thread, resolving a Promise when it finishes.
   *
   * Rejects only for usage errors — a bad argument, or a full queue. A
   * *failed compile* resolves with `{ ok: false, error }`, because a promise
   * rejection cannot carry structured diagnostics.
   */
  compile(request: CompileRequest): Promise<CompileResult>
  /**
   * Compile on the calling thread.
   *
   * Not a hedge. For batch workloads — N processes each looping over
   * documents — async scheduling is pure overhead and this is faster. It is
   * also the right call inside an existing `worker_thread`, where the pool
   * would just add a hop.
   */
  compileSync(request: CompileRequest): CompileResult
  get stats(): Stats
  /**
   * Registered font families, deduplicated and sorted. Useful for telling a
   * user why `text(font: "…")` did not match.
   */
  get fontFamilies(): Array<string>
  /**
   * Panic inside a pool job, on purpose.
   *
   * A Rust panic reaching Node aborts the whole process, so "we catch them"
   * has to be demonstrated rather than claimed. Compiled only under the
   * `test-hooks` feature; release builds do not contain it.
   */
  __panicInPool(): Promise<CompileResult>
}

export interface ClockOptions {
  /** Unix seconds. Pins the date, making output reproducible. */
  fixed?: number
  /**
   * Minutes **east** of UTC. Note the sign: JavaScript's
   * `getTimezoneOffset()` returns the opposite, so negate it.
   */
  offsetMinutes?: number
  /** Make `datetime.today()` an error in the document rather than a date. */
  unavailable?: boolean
}

export interface CompileFailure {
  /**
   * A stable machine-readable code: `COMPILE_FAILED`, `NO_FONTS`,
   * `PATH_VOCABULARY_EXHAUSTED`, and so on. Branch on this, never on
   * `message`.
   */
  code: string
  message: string
  diagnostics: Array<Diagnostic>
}

export interface CompileRequest {
  /**
   * The main document's source. Written to `/main.typ`.
   *
   * This is the normal entry point, and its shape is the point: **content
   * varies per request, the path never does.** Naming a file per request
   * leaks an interned path that is never freed.
   */
  source?: string
  /** Use an existing file as the main document instead of `source`. */
  main?: string
  /** Per-request files. Shadow the base layer for this compile only. */
  files?: Record<string, string | Uint8Array>
  clock?: ClockOptions
  pdf?: PdfOptions
}

/**
 * The outcome of a compile.
 *
 * A failed compile is **returned, not thrown**. A rejected promise can only
 * carry a `napi::Error`, which has room for a message and a status and nothing
 * else — diagnostics, positions, and hints would have to be flattened into a
 * string. Returning them keeps the boundary lossless and identical for the
 * sync and async paths, and `@emquad/core` turns a failure into a real `Error`
 * subclass, which is where a JS subclass belongs anyway.
 *
 * Argument and usage errors *do* throw: they are programming mistakes, not
 * outcomes.
 */
export interface CompileResult {
  ok: boolean
  /** Zero-copy. Present when `ok`. */
  pdf?: Buffer
  /**
   * Present even on success — warnings are the most likely place a
   * silently-wrong document announces itself.
   */
  warnings: Array<Diagnostic>
  pages?: number
  error?: CompileFailure
}

export interface CompilerOptions {
  /**
   * Font files. At least one face must parse, or construction fails with
   * `NO_FONTS` — typst would otherwise compile happily and emit a valid PDF
   * with every text run silently dropped and no diagnostics at all.
   */
  fonts: Array<Uint8Array>
  /**
   * The shared base VFS layer: templates, logos, data that does not change
   * per request. Built once; rebuilding it per compile would invalidate the
   * memo cache.
   */
  files?: Record<string, string | Uint8Array>
  /**
   * `@preview` package files. Fetching them is the resolver's job, in
   * TypeScript — this layer only stores what it is handed.
   */
  packages?: Array<PackageFile>
  /**
   * Compile threads. Defaults to `availableParallelism()`.
   *
   * There is no single correct value: Phase 0 measured scaling to 3.71× at
   * four threads on simple documents but a *collapse* to 0.46× on documents
   * with many page runs. Scaling is document-shape dependent.
   */
  poolSize?: number
  /** Queue depth before `compile()` refuses new work. Default 1024. */
  queueCapacity?: number
  /**
   * `comemo` eviction age, or `false` to disable eviction entirely.
   *
   * **The cache is process-global.** Two `Compiler` instances share it and
   * are not isolated from each other; this setting belongs to whichever pool
   * runs the compile.
   */
  cacheMaxAge?: number | boolean
  /**
   * Confine typst's internal rayon to one thread per compile.
   *
   * **Default `false`.** It buys nothing under this pool and costs ~15% at
   * low concurrency; see `emquad_engine::rayon`. The knob remains because
   * Phase 0's original measurement used a different mechanism that has not
   * been reproduced.
   */
  pinRayon?: boolean
}

export interface Diagnostic {
  /** `"error"` or `"warning"`. */
  severity: string
  message: string
  /** Absent when the diagnostic does not point into any file. */
  position?: Position
  hints: Array<Hint>
  trace: Array<TraceFrame>
}

/**
 * Evict the process-global `comemo` cache by hand.
 *
 * The pool does this automatically. This exists for `compileSync()` callers,
 * who never touch the pool and would otherwise grow the cache without bound.
 */
export declare function evictCache(maxAge?: number | undefined | null): void

export interface Hint {
  message: string
  /** A hint can point at different code than the diagnostic it belongs to. */
  position?: Position
}

export interface PackageFile {
  /** e.g. `@preview/cetz:0.4.2` */
  spec: string
  /**
   * Path within the package. Mount `typst.toml` too — typst reads it to find
   * the entrypoint, and an import fails without it.
   */
  path: string
  data: string | Uint8Array
}

export interface PageRangeOptions {
  /** 1-based, inclusive. Omit for "from the first page". */
  start?: number
  /** 1-based, inclusive. Omit for "to the last page". */
  end?: number
}

export interface PdfOptions {
  /**
   * Emit a tagged (accessible) PDF. Defaults to `true`, as upstream does.
   * The cost is size — Phase 0 measured up to +302% — not time.
   */
  tagged?: boolean
  pretty?: boolean
  /** SPDX-ish standard names: `1.4`–`2.0`, `a-1b`…`a-4e`, `ua-1`. */
  standards?: Array<string>
  /** Requires `tagged: false`. */
  pageRanges?: Array<PageRangeOptions>
  /** Must be stable across compiles of the same document, or omitted. */
  ident?: string
  /** A string, or `false` to omit the field. */
  creator?: string | boolean
  /** Unix seconds, or `false` to omit the timestamp. */
  timestamp?: number | boolean
}

export interface Position {
  /** A VFS path: `/main.typ`, or `@preview/cetz:0.4.2/lib.typ`. */
  file: string
  /** 1-based. */
  line: number
  /** 1-based, counted in characters rather than bytes. */
  column: number
}

/**
 * Lower the VFS path guard, for tests that need to reach it cheaply.
 *
 * Returns the limit actually set — raising it past typst's 65,535 cap is
 * refused, since beyond that the guard could not fire before typst's own
 * panic.
 */
export declare function setPathLimit(limit: number): number

/** Pool and interner counters, for metrics. */
export interface Stats {
  poolSize: number
  queueCapacity: number
  /** Jobs waiting, not counting those in flight. */
  queued: number
  /**
   * Distinct VFS paths interned process-wide, including any typst interned
   * itself. **This is the number that predicts a crash** — export
   * `interned / pathLimit`.
   */
  internedPaths: number
  /**
   * Paths interned through this library's wrapper. Never exceeds
   * `internedPaths`.
   */
  trackedPaths: number
  /** Where the guard trips. */
  pathLimit: number
  /** Typst's hard cap, past which it panics. */
  pathCap: number
}

export interface TraceFrame {
  message: string
  position?: Position
}

/**
 * The exact Typst version this binary was built against.
 *
 * Typst is pre-1.0 and rendering changes across minor releases, so a user
 * correlating output differences needs this at runtime, not just in a README.
 */
export declare function typstVersion(): string
